### ISSUE TITLE
throws Error when `.xls` file provided

### ISSUE THREAD

**Issue by pr4j3sh** [asteng88/PyPredict#4]
I tried providing `.xls` file and the program throws error that the file provided is not a zip file. However, it works fine for `.xlsx` files.

## screenshots
![ss-20241001-172751Z-current](https://github.com/user-attachments/assets/e4641dd5-1790-4395-a4e2-c730e67c4426)
![ss-20241001-172757Z-current](https://github.com/user-attachments/assets/f626879f-28f4-4787-a7f4-783462de76df)

## deduction
the error occurs as [openpyxl](https://openpyxl.readthedocs.io/en/stable/#introduction) cannot handle `.xls` files.

## suggestion
adding a conversion method for `.xls` files to be converted into `.xlsx` files.

**Comment by asteng88** [comment]
@prajeshElEvEn 
I'll take this one and get it fixed. Thanks for the heads up with the .xls extension.

**Comment by asteng88** [comment]
Added conversion through using xlrd library to convert xls to xlsx
